name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check.outputs.should_skip }}
    steps:
      - name: Check for #skip in commits
        id: check
        run: |
          COMMITS='${{ toJson(github.event.commits) }}'
          if echo "$COMMITS" | grep -q "#skip"; then
            echo "should_skip=true" >> $GITHUB_OUTPUT
            echo "Found #skip in commit messages, will skip deployment"
          else
            echo "should_skip=false" >> $GITHUB_OUTPUT
            echo "No #skip found, will proceed with deployment"
          fi

  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "Error: dist/index.html not found"
            exit 1
          fi
          echo "Build verification successful"
      - name: Build Success Notification
        uses: rjstone/discord-webhook-notify@v2
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          text: A new version of Pokedex deployed
          description: "to https://full-stack-open-pokedex-teal.vercel.app/ by shanmengqi2"
          footer: "Severity: Informational"
      - name: Build Failure Notification
        uses: rjstone/discord-webhook-notify@v2
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          text: Build failed
          description: "commit ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} by shanmengqi2 broke the build :("
          footer: "Severity: Error"

  tag_release:
    needs: [check_skip, simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.check_skip.outputs.should_skip != 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
